package pieces

func StartingPlayingPieces() [8][8]PlayingPiece {
	result := [8][8]PlayingPiece{
		{
			NewRook(BLACK, Position{row: 0, col: 0, boardRow: '8', boardCol: 'a'}),
			NewKnight(BLACK, Position{row: 0, col: 1, boardRow: '8', boardCol: 'b'}),
			NewBishop(BLACK, Position{row: 0, col: 2, boardRow: '8', boardCol: 'c'}),
			NewQueen(BLACK, Position{row: 0, col: 3, boardRow: '8', boardCol: 'd'}),
			NewKing(BLACK, Position{row: 0, col: 4, boardRow: '8', boardCol: 'e'}),
			NewBishop(BLACK, Position{row: 0, col: 5, boardRow: '8', boardCol: 'f'}),
			NewKnight(BLACK, Position{row: 0, col: 6, boardRow: '8', boardCol: 'g'}),
			NewRook(BLACK, Position{row: 0, col: 7, boardRow: '8', boardCol: 'h'}),
		},
		{
			NewPawn(BLACK, Position{row: 1, col: 0, boardRow: '7', boardCol: 'a'}),
			NewPawn(BLACK, Position{row: 1, col: 1, boardRow: '7', boardCol: 'b'}),
			NewPawn(BLACK, Position{row: 1, col: 2, boardRow: '7', boardCol: 'c'}),
			NewPawn(BLACK, Position{row: 1, col: 3, boardRow: '7', boardCol: 'd'}),
			NewPawn(BLACK, Position{row: 1, col: 4, boardRow: '7', boardCol: 'e'}),
			NewPawn(BLACK, Position{row: 1, col: 5, boardRow: '7', boardCol: 'f'}),
			NewPawn(BLACK, Position{row: 1, col: 6, boardRow: '7', boardCol: 'g'}),
			NewPawn(BLACK, Position{row: 1, col: 7, boardRow: '7', boardCol: 'h'}),
		},
		{
			NewNoPiece(NONE, Position{row: 2, col: 0, boardRow: '6', boardCol: 'a'}),
			NewNoPiece(NONE, Position{row: 2, col: 1, boardRow: '6', boardCol: 'b'}),
			NewNoPiece(NONE, Position{row: 2, col: 2, boardRow: '6', boardCol: 'c'}),
			NewNoPiece(NONE, Position{row: 2, col: 3, boardRow: '6', boardCol: 'd'}),
			NewNoPiece(NONE, Position{row: 2, col: 4, boardRow: '6', boardCol: 'e'}),
			NewNoPiece(NONE, Position{row: 2, col: 5, boardRow: '6', boardCol: 'f'}),
			NewNoPiece(NONE, Position{row: 2, col: 6, boardRow: '6', boardCol: 'g'}),
			NewNoPiece(NONE, Position{row: 2, col: 7, boardRow: '6', boardCol: 'h'}),
		},
		{
			NewNoPiece(NONE, Position{row: 3, col: 0, boardRow: '5', boardCol: 'a'}),
			NewNoPiece(NONE, Position{row: 3, col: 1, boardRow: '5', boardCol: 'b'}),
			NewNoPiece(NONE, Position{row: 3, col: 2, boardRow: '5', boardCol: 'c'}),
			NewNoPiece(NONE, Position{row: 3, col: 3, boardRow: '5', boardCol: 'd'}),
			NewNoPiece(NONE, Position{row: 3, col: 4, boardRow: '5', boardCol: 'e'}),
			NewNoPiece(NONE, Position{row: 3, col: 5, boardRow: '5', boardCol: 'f'}),
			NewNoPiece(NONE, Position{row: 3, col: 6, boardRow: '5', boardCol: 'g'}),
			NewNoPiece(NONE, Position{row: 3, col: 7, boardRow: '5', boardCol: 'h'}),
		},
		{
			NewNoPiece(NONE, Position{row: 4, col: 0, boardRow: '4', boardCol: 'a'}),
			NewNoPiece(NONE, Position{row: 4, col: 1, boardRow: '4', boardCol: 'b'}),
			NewNoPiece(NONE, Position{row: 4, col: 2, boardRow: '4', boardCol: 'c'}),
			NewNoPiece(NONE, Position{row: 4, col: 3, boardRow: '4', boardCol: 'd'}),
			NewNoPiece(NONE, Position{row: 4, col: 4, boardRow: '4', boardCol: 'e'}),
			NewNoPiece(NONE, Position{row: 4, col: 5, boardRow: '4', boardCol: 'f'}),
			NewNoPiece(NONE, Position{row: 4, col: 6, boardRow: '4', boardCol: 'g'}),
			NewNoPiece(NONE, Position{row: 4, col: 7, boardRow: '4', boardCol: 'h'}),
		},
		{
			NewNoPiece(NONE, Position{row: 5, col: 0, boardRow: '3', boardCol: 'a'}),
			NewNoPiece(NONE, Position{row: 5, col: 1, boardRow: '3', boardCol: 'b'}),
			NewNoPiece(NONE, Position{row: 5, col: 2, boardRow: '3', boardCol: 'c'}),
			NewNoPiece(NONE, Position{row: 5, col: 3, boardRow: '3', boardCol: 'd'}),
			NewNoPiece(NONE, Position{row: 5, col: 4, boardRow: '3', boardCol: 'e'}),
			NewNoPiece(NONE, Position{row: 5, col: 5, boardRow: '3', boardCol: 'f'}),
			NewNoPiece(NONE, Position{row: 5, col: 6, boardRow: '3', boardCol: 'g'}),
			NewNoPiece(NONE, Position{row: 5, col: 7, boardRow: '3', boardCol: 'h'}),
		},
		{
			NewPawn(WHITE, Position{row: 6, col: 0, boardRow: '2', boardCol: 'a'}),
			NewPawn(WHITE, Position{row: 6, col: 1, boardRow: '2', boardCol: 'b'}),
			NewPawn(WHITE, Position{row: 6, col: 2, boardRow: '2', boardCol: 'c'}),
			NewPawn(WHITE, Position{row: 6, col: 3, boardRow: '2', boardCol: 'd'}),
			NewPawn(WHITE, Position{row: 6, col: 4, boardRow: '2', boardCol: 'e'}),
			NewPawn(WHITE, Position{row: 6, col: 5, boardRow: '2', boardCol: 'f'}),
			NewPawn(WHITE, Position{row: 6, col: 6, boardRow: '2', boardCol: 'g'}),
			NewPawn(WHITE, Position{row: 6, col: 7, boardRow: '2', boardCol: 'h'}),
		},
		{
			NewRook(WHITE, Position{row: 7, col: 0, boardRow: '1', boardCol: 'a'}),
			NewKnight(WHITE, Position{row: 7, col: 1, boardRow: '1', boardCol: 'b'}),
			NewBishop(WHITE, Position{row: 7, col: 2, boardRow: '1', boardCol: 'c'}),
			NewQueen(WHITE, Position{row: 7, col: 3, boardRow: '1', boardCol: 'd'}),
			NewKing(WHITE, Position{row: 7, col: 4, boardRow: '1', boardCol: 'e'}),
			NewBishop(WHITE, Position{row: 7, col: 5, boardRow: '1', boardCol: 'f'}),
			NewKnight(WHITE, Position{row: 7, col: 6, boardRow: '1', boardCol: 'g'}),
			NewRook(WHITE, Position{row: 7, col: 7, boardRow: '1', boardCol: 'h'}),
		},
	}
	return result
}
